%% Exact linearization of the Simulink model Trim_Model_ForStudent
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.3 and Simulink Control Design (TM) 5.0.
%
% Generated on: 10-Jul-2019 20:19:22

%% Specify the model name
model = 'Trim_Model_ForStudent';

%% Specify the analysis I/Os
% Use root level inports and outports in Trim_Model_ForStudent
% by passing no input argument to the linearize command for analysis I/Os

%% Specify the operating point
% Create the operating point variable op_trim2 using model initial condition as a starting point
op = operpoint('Trim_Model_ForStudent');
% Set the states in the model with different values than model initial condition
% State (1) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/p
op.States(1).x = 1.429059328638582e-22;
% State (2) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/phi
op.States(2).x = -2.160861730256426e-09;
% State (3) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/psi
op.States(3).x = -4.398965568859309e-17;
% State (4) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/q
op.States(4).x = 4.855247531467947e-23;
% State (5) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/r
op.States(5).x = 1.367119704451098e-23;
% State (6) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/theta
op.States(6).x = 0.03721973753909018;
% State (7) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/u
op.States(7).x = 49.96537127633789;
% State (8) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/v
op.States(8).x = -9.750444872358897e-07;
% State (9) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/w
op.States(9).x = 1.860557233112767;
% State (10) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/xe
op.States(10).x = 4.22069000568345e-17;
% State (11) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/ye
op.States(11).x = -1.585300829148584e-16;
% Set the inputs in the model with different values than model initial condition
% Input (1) - Trim_Model_ForStudent/Xi
op.Inputs(1).u = 4.518622816403486e-10;
% Input (2) - Trim_Model_ForStudent/Eta
op.Inputs(2).u = 0.0562147400758847;
% Input (3) - Trim_Model_ForStudent/Throttle
op.Inputs(3).u = 0.32112834930933;
% Input (4) - Trim_Model_ForStudent/Zeta
op.Inputs(4).u = -2.662298671781111e-08;


%% Linearize the model
sys = linearize(model,opreport);

%% Plot the resulting linearization
% step(sys)

