%% Search for a specified operating point for the model - Trim_Model_ForStudent.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.3 and Simulink Control Design (TM) 5.0.
%
% Generated on: 09-Jul-2019 23:36:36
%%
Tr_V = 50;
Tr_ze = -2000;

%% Specify the model name
model = 'Trim_Model_ForStudent';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/p
% - Default model initial conditions are used to initialize optimization.

% State (2) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/phi
% - Default model initial conditions are used to initialize optimization.

% State (3) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/psi
% - Default model initial conditions are used to initialize optimization.

% State (4) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/q
% - Default model initial conditions are used to initialize optimization.

% State (5) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/r
% - Default model initial conditions are used to initialize optimization.

% State (6) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/theta
% - Default model initial conditions are used to initialize optimization.

% State (7) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/u
% - Default model initial conditions are used to initialize optimization.

% State (8) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/v
% - Default model initial conditions are used to initialize optimization.

% State (9) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/w
% - Default model initial conditions are used to initialize optimization.

% State (10) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/xe
% - Default model initial conditions are used to initialize optimization.
opspec.States(10).SteadyState = false;

% State (11) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/ye
% - Default model initial conditions are used to initialize optimization.
opspec.States(11).SteadyState = false;

% State (12) - Trim_Model_ForStudent/Flight_physics|Flight_Physics__STD/Dynamic&KinematlcEquations/Equations/ze
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - Trim_Model_ForStudent/Xi
% - Default model initial conditions are used to initialize optimization.

% Input (2) - Trim_Model_ForStudent/Eta
% - Default model initial conditions are used to initialize optimization.

% Input (3) - Trim_Model_ForStudent/Throttle
% - Default model initial conditions are used to initialize optimization.

% Input (4) - Trim_Model_ForStudent/Zeta
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - Trim_Model_ForStudent/VEL_K_R_E
% - Default model initial conditions are used to initialize optimization.

% Output (2) - Trim_Model_ForStudent/POS_R_E
opspec.Outputs(2).y = [0;0;Tr_ze];
opspec.Outputs(2).Known = [false;false;true];

% Output (3) - Trim_Model_ForStudent/ATT_EULER
% - Default model initial conditions are used to initialize optimization.

% Output (4) - Trim_Model_ForStudent/M_BE
% - Default model initial conditions are used to initialize optimization.

% Output (5) - Trim_Model_ForStudent/VEL_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (6) - Trim_Model_ForStudent/ROT_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (7) - Trim_Model_ForStudent/ROT_DOT_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (8) - Trim_Model_ForStudent/VEL_DOT_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (9) - Trim_Model_ForStudent/FUEL_Availible
% - Default model initial conditions are used to initialize optimization.

% Output (10) - Trim_Model_ForStudent/VEL_K_R_ABS
opspec.Outputs(10).y = Tr_V;
opspec.Outputs(10).Known = true;

% Output (11) - Trim_Model_ForStudent/Chi_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (12) - Trim_Model_ForStudent/Gamma_K_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (13) - Trim_Model_ForStudent/Alpha_A_R_B
% - Default model initial conditions are used to initialize optimization.

% Output (14) - Trim_Model_ForStudent/Beta_A_R_B
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);


%% save data
datapath = [Root_Folder,'/Trim&Linearization/ResultData'];
% save([datapath,'/Trimpoint001'],'opreport','Tr_V','Tr_alpha','Tr_Gamma','Tr_flap','Tr_flag');
save([datapath,'/Trimpoint001'],'opreport','Tr_V','Tr_ze');
